### ISSUE TITLE
params can be content descriptors and should allow `deprecated` field

### ISSUE THREAD

**Issue by shanejonas** [open-rpc/meta-schema#188]
- https://spec.open-rpc.org/#method-object
- https://spec.open-rpc.org/#content-descriptor-object

iiuc, `Method`s can have `ContentDescriptor`s as `Params`. `Params` can have a `deprecated` field. The playground currently tells me this is an error: `Property deprecated is not allowed`.

![image](https://user-images.githubusercontent.com/45600330/76703497-1157f900-66a0-11ea-9e6c-4fbc61a2ae0f.png)

rel https://github.com/open-rpc/playground/issues/372

**Comment by meowsbits** [comment]
:information_source: migrated from https://github.com/open-rpc/playground/issues/372
