### ISSUE TITLE
JSONSchema.minItems cannot unmarshal from number

### ISSUE THREAD

**Issue by meowsbits** [open-rpc/meta-schema#221]
**Describe the bug**
```
err="json: cannot unmarshal number into Go struct field JSONSchema.minItems of type meta_schema.AllOfAnyXumYU1GWInteger7Bd9WOt20HjcoOji"
```

This might be an issue with json-schema-to-types, but I found it here. Possibly related, or similar to, https://github.com/etclabscore/json-schema-to-types/issues/45.

**Comment by meowsbits** [comment]
beep

**Comment by BelfordZ** [comment]
@meowsbits can you help me repro this bug if it still exists?

This repo is using tooling from json-schema-tools now, so it may be fixed.
