### ISSUE TITLE
content descriptors `examples` should match exactly the schema of the content descriptor

### ISSUE THREAD

**Issue by shanejonas** [open-rpc/meta-schema#33]
![image](https://user-images.githubusercontent.com/364566/52926320-1ce4bf00-32ea-11e9-9f1a-db6f8ed213c3.png)

**Comment by BelfordZ** [comment]
AFAIK it is not possible to constrain this with JSON schema alone.

However, this may be something we can accommodate for as a layer above this meta schema.

gonna leave this open in case any good ideas come along.
