### ISSUE TITLE
Pristine this repo

### ISSUE THREAD

**Issue by shanejonas** [open-rpc/meta-schema#76]
**Describe the feature you would like**
This repo should be using pristine to get better baseline documentation and encourage contributions

**Describe the solution**
https://github.com/etclabscore/pristine#how-to-use-pristine-in-your-project

**Comment by fosgate29** [comment]
It is possible to close this issue.
Pull request [feat: added pristine](https://github.com/open-rpc/meta-schema/pull/102) fixed this issue.
